export const database = {
  at: "2023-05-18T18:54:13.525Z",
  products: [
    {
      description: "nisi incididunt nulla in",
      name: "ipsum",
      price: 791.22,
      tmpProperty: undefined,
      activePromoId: 72,
    },
    {},
    {},
    {},
    {},
    {
      description: "labore fugiat irure cupidatat",
      name: "consectetur",
      price: 1599.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laboris quis ex amet",
      name: "ea",
      price: 1270.37,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam dolor ipsum mollit",
      name: "mollit",
      price: 1456.15,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "consequat fugiat irure laborum",
      name: "proident",
      price: 1074.74,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor laborum eiusmod sit",
      name: "nisi",
      price: 1296.99,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {},
    {},
    {},
    {
      description: "nulla in ex eiusmod",
      name: "dolor",
      price: 825.17,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: "amet in reprehenderit pariatur",
      name: "non",
      price: 1182.71,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: "labore est voluptate ullamco",
      name: "dolore",
      price: 798.35,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: "esse in incididunt ea",
      name: "enim",
      price: 1680.03,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {
      description: "et esse amet et",
      name: "irure",
      price: 1888.85,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation officia nostrud aute",
      name: "eu",
      price: 855.36,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {
      description: "labore ea excepteur cillum",
      name: "incididunt",
      price: 697.45,
      tmpProperty: undefined,
      activePromoId: 74,
    },
    {
      description: "culpa proident incididunt laborum",
      name: "dolore",
      price: 189,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "do esse velit nisi",
      name: "excepteur",
      price: 1367.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "esse fugiat magna culpa",
      name: "aliquip",
      price: 286.86,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: "consequat fugiat do sint",
      name: "aliquip",
      price: 521.62,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nostrud sint mollit ea",
      name: "sint",
      price: 1383.87,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem qui duis enim",
      name: "eu",
      price: 109.22,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consectetur et cillum aliquip",
      name: "laboris",
      price: 1420.18,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat voluptate quis aliqua",
      name: "duis",
      price: 811.21,
      tmpProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "elit sunt ad ullamco",
      name: "anim",
      price: 1705.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua laboris adipisicing et",
      name: "dolore",
      price: 1057.16,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ipsum est enim proident",
      name: "labore",
      price: 1927.42,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation voluptate nostrud amet",
      name: "dolor",
      price: 1606.36,
      tmpProperty: undefined,
      activePromoId: 21,
    },
    {
      description: "incididunt ullamco non labore",
      name: "cupidatat",
      price: 1542.34,
      tmpProperty: undefined,
      activePromoId: 68,
    },
    {
      description: "magna pariatur incididunt laboris",
      name: "in",
      price: 276.46,
      tmpProperty: undefined,
      activePromoId: 57,
    },
    {
      description: "consequat amet dolor minim",
      name: "ex",
      price: 632.71,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: "amet do in dolore",
      name: "anim",
      price: 262.83,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "tempor eu ex do",
      name: "amet",
      price: 1646.47,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "anim est sint consequat",
      name: "aliquip",
      price: 491.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "enim pariatur sit ipsum",
      name: "labore",
      price: 384.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolore fugiat voluptate voluptate",
      name: "commodo",
      price: 201.88,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: "nostrud aute ut velit",
      name: "ipsum",
      price: 1717.75,
      tmpProperty: undefined,
      activePromoId: 14,
    },
    {
      description: "dolore in commodo nostrud",
      name: "tempor",
      price: 856.79,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "sit sit aliqua aute",
      name: "sint",
      price: 934.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem ea elit eiusmod",
      name: "dolor",
      price: 229.17,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nulla irure amet nulla",
      name: "veniam",
      price: 395.88,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "ad qui sunt culpa",
      name: "deserunt",
      price: 1781.42,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: "eu consequat id non",
      name: "sit",
      price: 1510.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ullamco sunt nostrud nisi",
      name: "eu",
      price: 184.55,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: "culpa enim ipsum aliqua",
      name: "nulla",
      price: 1240.58,
      tmpProperty: undefined,
      activePromoId: 89,
    },
    {
      description: "cupidatat cupidatat irure nulla",
      name: "id",
      price: 1287.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "anim deserunt tempor sunt",
      name: "voluptate",
      price: 561.93,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: "incididunt mollit mollit laborum",
      name: "ullamco",
      price: 1352.75,
      tmpProperty: undefined,
      activePromoId: 59,
    },
    {
      description: "dolore elit laborum id",
      name: "Lorem",
      price: 426.15,
      tmpProperty: undefined,
      activePromoId: 2,
    },
    {
      description: "est excepteur incididunt consectetur",
      name: "laboris",
      price: 1181.88,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "adipisicing consectetur consequat incididunt",
      name: "nisi",
      price: 1533.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aute cillum enim id",
      name: "Lorem",
      price: 1019.79,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "duis magna occaecat aliquip",
      name: "fugiat",
      price: 199.41,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "commodo tempor proident aliquip",
      name: "do",
      price: 836.85,
      tmpProperty: undefined,
      activePromoId: 24,
    },
    {
      description: "voluptate id enim reprehenderit",
      name: "dolore",
      price: 1812.76,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "excepteur nostrud ullamco veniam",
      name: "dolor",
      price: 158.68,
      tmpProperty: undefined,
      activePromoId: 11,
    },
    {
      description: "eiusmod aliquip incididunt et",
      name: "tempor",
      price: 1402.87,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation anim nostrud occaecat",
      name: "dolore",
      price: 621.04,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis est aliqua enim",
      name: "velit",
      price: 930.97,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "voluptate sit Lorem ea",
      name: "tempor",
      price: 562.83,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad culpa exercitation aliqua",
      name: "velit",
      price: 1687.25,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {
      description: "esse ad quis qui",
      name: "nostrud",
      price: 1447.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "irure ex consectetur nostrud",
      name: "eiusmod",
      price: 369.59,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "eu laboris veniam non",
      name: "dolor",
      price: 1392.82,
      tmpProperty: undefined,
      activePromoId: 46,
    },
    {
      description: "ad laborum ullamco minim",
      name: "tempor",
      price: 881.84,
      tmpProperty: undefined,
      activePromoId: 27,
    },
    {
      description: "veniam labore eiusmod dolor",
      name: "labore",
      price: 869.46,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consectetur Lorem exercitation dolor",
      name: "tempor",
      price: 441.45,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: "incididunt officia nisi laboris",
      name: "sunt",
      price: 470.08,
      tmpProperty: undefined,
      activePromoId: 39,
    },
    {
      description: "ullamco nostrud dolor quis",
      name: "et",
      price: 612.24,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aute sunt aliquip eiusmod",
      name: "fugiat",
      price: 590.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit ex esse non",
      name: "esse",
      price: 1568.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sunt nisi id sit",
      name: "ad",
      price: 1968.29,
      tmpProperty: undefined,
      activePromoId: 60,
    },
    {
      description: "mollit culpa ea sint",
      name: "occaecat",
      price: 1039.95,
      tmpProperty: undefined,
      activePromoId: 35,
    },
    {
      description: "fugiat velit amet qui",
      name: "laboris",
      price: 131.35,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "reprehenderit in nisi et",
      name: "mollit",
      price: 1199.86,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: "nulla culpa in elit",
      name: "exercitation",
      price: 1160.33,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "pariatur in et incididunt",
      name: "ut",
      price: 1918.68,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "aliquip nisi officia eu",
      name: "quis",
      price: 1995.41,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad ea incididunt ullamco",
      name: "ad",
      price: 1796.34,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: "adipisicing esse adipisicing Lorem",
      name: "in",
      price: 1775.78,
      tmpProperty: undefined,
      activePromoId: 51,
    },
    {
      description: "anim quis voluptate cupidatat",
      name: "pariatur",
      price: 532.3,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: "eu magna duis cillum",
      name: "Lorem",
      price: 1898.94,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "irure pariatur duis magna",
      name: "amet",
      price: 1992.98,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: "cillum voluptate Lorem fugiat",
      name: "id",
      price: 1128.42,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem officia duis ullamco",
      name: "elit",
      price: 1347.57,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu laborum ut sit",
      name: "veniam",
      price: 1106.16,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "do et sit qui",
      name: "labore",
      price: 1644.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laborum adipisicing qui dolor",
      name: "veniam",
      price: 1093.15,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ipsum eiusmod nisi cillum",
      name: "irure",
      price: 283.02,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat sunt mollit adipisicing",
      name: "enim",
      price: 1251.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim nulla nostrud duis",
      name: "excepteur",
      price: 363.73,
      tmpProperty: undefined,
      activePromoId: 11,
    },
    {
      description: "eiusmod irure aliquip aliqua",
      name: "amet",
      price: 1289.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "in consequat culpa quis",
      name: "nulla",
      price: 1780.07,
      tmpProperty: undefined,
      activePromoId: 74,
    },
    {
      description: "proident sint qui laboris",
      name: "qui",
      price: 635.74,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: "consequat adipisicing nulla occaecat",
      name: "reprehenderit",
      price: 106.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "qui eu quis aliquip",
      name: "magna",
      price: 958.91,
      tmpProperty: undefined,
      activePromoId: 79,
    },
    {
      description: "proident nisi duis ea",
      name: "magna",
      price: 438.93,
      tmpProperty: undefined,
      activePromoId: 90,
    },
    {
      description: "pariatur pariatur mollit cupidatat",
      name: "nostrud",
      price: 553.3,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nulla non dolore nisi",
      name: "ipsum",
      price: 1555.68,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat pariatur tempor sint",
      name: "consequat",
      price: 1257.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat duis incididunt aliqua",
      name: "dolor",
      price: 1549.48,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ea minim sunt aliqua",
      name: "eu",
      price: 139.54,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu aute duis anim",
      name: "cillum",
      price: 180.53,
      tmpProperty: undefined,
      activePromoId: 6,
    },
  ],
};
